vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        property_cv:
            uri_prefix: /cvs
            upload_destination: '%kernel.project_dir%/public/cvs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
